### PR TITLE
Avatar extended

### PR DESCRIPTION
**Pull request by yariplus**
Added features from nodebb-plugin-gravatar-extended

Also, added the force flag to the customDefault, without it the option is equivalent to defaultIcon.

### CODE REVIEW

**Comment by yariplus** [comment]
https://github.com/JLChnToZ/nodebb-plugin-gravatar-extended/issues/3

**Comment by julianlam** [comment]
v1.0.4, thanks for the hard work @yariplus !! :smile:

**Comment by JLChnToZ** [comment]
@yariplus thanks for your help very much!

**Comment by mllnd** [comment]
Thanks! :relaxed:

**Pull request merged**
